# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

variables:
  branch : 'master'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: 
    git remote add github https://jwc-gh:githu879@github.com/jwc-gh/Wichian.git
- script: 
    git push -u github $(branch)

  displayName: 'Sync Wichian From Azure To Github'
