# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'


steps:
- script: 
    git remote add github https://wichian@qq.com:githu879@github.com/jwc-gh/Wichian.git
    git checkout -b $('main')
    git push -u github $('main')

  displayName: 'Sync Wichian From Azure To Github'
